# Generated by Django 5.0.3 on 2024-04-08 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sales_code_remove_sales_sub_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
