# Generated by Django 5.0.3 on 2024-04-18 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='description',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='name',
        ),
        migrations.AddField(
            model_name='materials',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.products'),
            preserve_default=False,
        ),
    ]
