# Generated by Django 5.0.3 on 2024-05-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField( unique=True),
            preserve_default=False,
        ),
    ]
