# Generated by Django 5.0.3 on 2024-05-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
